### ISSUE TITLE
Java 11 migration

### ISSUE THREAD

**Issue by Zethson** [qbicsoftware/parent-poms#31]
Hey,

we could evaluate whether or not we can upgrade to Java 11, the latest LTS.
Versions 9-11 feature some neat improvements such as:
- modules
- local variable type inference
- ahead of time compilation
- local variable syntax for lambdas

The full list of features is listed here: 
http://openjdk.java.net/projects/jdk9/
http://openjdk.java.net/projects/jdk/10/
http://openjdk.java.net/projects/jdk/11/

Things to keep in mind:
- Jetty 9.4.x already runs on JDK 11
- JavaFX has been removed from the JDK -> JavaFX 11 dependency has to be included

**Comment by chahuistle** [comment]
Thanks for bringing this up! 

We can also combine with the following issues:

https://github.com/qbicsoftware/parent-poms/issues/28
https://github.com/qbicsoftware/parent-poms/issues/5

**Comment by Zethson** [comment]
I ran travis on the postman-core-lib with openjdk11.

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.8:run (compile) on project postman-core-lib: An Ant BuildException has occured: BUG! exception in phase 'semantic analysis' in source unit '/home/travis/build/qbicsoftware/postman-core-lib/src/main/groovy/life/qbic/util/RegexFilterDownloadUtil.groovy' null
[ERROR] around Ant part ...<groovyc destdir="/home/travis/build/qbicsoftware/postman-core-lib/target/classes" srcdir="/home/travis/build/qbicsoftware/postman-core-lib/src/main/groovy" encoding="UTF-8">... @ 8:177 in /home/travis/build/qbicsoftware/postman-core-lib/target/antrun/build-main.xml: UnsupportedOperationException

It may not play nicely without shitty groovy ant build script.

**Comment by Zethson** [comment]
`Execution default-cli of goal org.codehaus.mojo:cobertura-maven-plugin:2.7:instrument failed: Plugin org.codehaus.mojo:cobertura-maven-plugin:2.7 or one of its dependencies could not be resolved: Could not find artifact com.sun:tools:jar:0 at specified path /usr/local/lib/jvm/openjdk11/../lib/tools.jar `

When building variantstore against JDK11. Since the latest release of the cobertura-maven plugin is from 2015, I expect it to not be JDK 11 compatible. We should look for alternatives.

**Comment by Zethson** [comment]
https://github.com/jacoco/jacoco/issues/663

Jacoco seems to support JDK11+

**Comment by KochTobi** [comment]
closed due to inactivity
