### ISSUE TITLE
Service POM 2.2.0-SNAPSHOT prevents service authentication 

### ISSUE THREAD

**Issue by sven1103** [qbicsoftware/parent-poms#49]
This is only relevant for the QBiC services build with micronaut.io

The current 2.2.0-SNAPSHOT prevents the integration tests of the sample tracking service from passing. The authentication seems not to work anymore, all endpoints return a 401 response.

As a lot of changes are introduced since service pom 2.1.0, I suggest to investigate this further, before making a new release of the parent poms.

**Comment by KochTobi** [comment]
Is this resolved?

**Comment by KochTobi** [comment]
@christopher-mohr  is this still an issue?

**Comment by christopher-mohr** [comment]
> @christopher-mohr is this still an issue?

Not sure what this issue refers to exactly. One issue is definitely that it requires a `userroles config` to be defined and present, otherwise the service will fail.

**Comment by KochTobi** [comment]
Thanks, I guess that the missing `userroles.config` was the issue. I will close this issue now.
